[project]
name = "ctw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.4,<2.5",
    "scipy>=1.17,<1.18",
    "pandas>=2.3,<3.1",
    "matplotlib>=3.9,<3.11",
    "anytree>=2.13.0",
    "graphviz==0.21",
    "requests>=2.33.1",
    "ucimlrepo>=0.0.7",
    "scip>=0.1.12",
    "wfdb==4.3.1",
    "tqdm>=4.67.3",
]
